print('30/05/24')
print('Right now Im feeling grate, Im so excited to get involve in al off this world')
print('Im just wanna be a good programmer and make a living from it!')
print('Just keep calm and relax, this gonna be a really good way to improve your skills in coding')
print('👽')